version: '3'

services:
  # Scala 3
  sbt-3:
    # Tags are: <JDK version>_<sbt version>_<Scala version>
    image: sbtscala/scala-sbt:graalvm-ce-22.3.0-b2-java17_1.8.2_3.2.1
    extends:
      file: common.yml
      service: scala-build

  # Scala 2.12
  sbt:
    image: sbtscala/scala-sbt:graalvm-ce-22.3.0-b2-java17_1.8.2_2.12.17
    extends:
      file: common.yml
      service: scala-build
