version: '3'

services:
  sbt:
    # Tags are: <JDK version>_<sbt version>_<Scala version>
    image: sbtscala/scala-sbt:graalvm-ce-22.3.0-b2-java17_1.8.2_3.2.1
    volumes:
      - ./:/root/
    entrypoint:
      [ "sbt" ]
